### ISSUE TITLE
Change locale

### ISSUE THREAD

**Issue by SFocus** [acoutts/flutter_libphonenumber#53]
I'm trying to show a list of countries with phone numbers in some locale but can't do this. Library get country name in system locale.  It is possible to change it?

**Comment by acoutts** [comment]
Can you give an example of what the output is now and what it should be?

**Comment by SFocus** [comment]
For example my device locale is German and it turns out that when I get the list of countries, they are in German locale, although in the application I need to show the list in English. I'm using getAllSupportedRegions()

**Comment by acoutts** [comment]
Right, i just want to better understand what the german locale vs english looks like for the country names.

**Comment by SFocus** [comment]
Okay, here's a better example:

Ukraine is "Україна" but should be Ukraine

**Comment by acoutts** [comment]
That's odd as that looks like ukranian not german..
I think you just need to do the translation yourself, but I would assume if a person has their phone set in german they'd be comfortable seeing the countries in german too.
The limitation is from the PhoneNumberKit and libphonenumber packages - we can't specify the locale there, they just take the current device locale too.

**Comment by SFocus** [comment]
Okay, thanks for the explanation.
