### ISSUE TITLE
Pod install error (ios)

### ISSUE THREAD

**Issue by temcewen** [acoutts/flutter_libphonenumber#59]
I believe this is the same thing that was happening on a previous [issue:](https://github.com/acoutts/flutter_libphonenumber/issues/56)

[!] CocoaPods could not find compatible versions for pod "PhoneNumberKit/PhoneNumberKitCore":
  In Podfile:
    PhoneNumberKit (from `https://github.com/marmelroy/PhoneNumberKit`) was resolved to 3.7.3, which depends on
      PhoneNumberKit/PhoneNumberKitCore (= 3.7.3)

    flutter_libphonenumber_ios (from `.symlinks/plugins/flutter_libphonenumber_ios/ios`) was resolved to 1.1.4, which depends on
      PhoneNumberKit/PhoneNumberKitCore (= 3.6.6)

Specs satisfying the `PhoneNumberKit/PhoneNumberKitCore (= 3.7.3), PhoneNumberKit/PhoneNumberKitCore (= 3.6.6)` dependency were found, but they required a higher minimum deployment target.

**Comment by woelmer** [comment]
If you get rid of `pod "PhoneNumberKit", :git => "https://github.com/marmelroy/PhoneNumberKit"` in your Podfile it fixed the issue for me.  It was[ mentioned here](https://github.com/acoutts/flutter_libphonenumber/issues/56#issuecomment-1677260705) that this is no longer necessary.

**Comment by acoutts** [comment]
Yup the trick from @woelmer should fix this.
