### ISSUE TITLE
iOS/android different libs

### ISSUE THREAD

**Issue by vasilich6107** [acoutts/flutter_libphonenumber#75]
Could you clarify the reason on using different libs for android and ios
there could be different behavior and bugs which make the lib usage more like an unexpected thing

**Comment by acoutts** [comment]
The official libphonenumber library is only supported in java, c++ and javascript. Maybe you can make it work with dart:ffi with c++ but it's much easier to just use the more common PhoneNumberKIt for ios/macos.
