### ISSUE TITLE
Australian numbers starting from +61-493.. are not being validated on Android. Please update underlying libphonenumber to latest version.

### ISSUE THREAD

**Issue by sakinaboriwala** [acoutts/flutter_libphonenumber#77]
Latest libphonenumber version is **8.13.42**, the library currently uses **8.12.52**

Australian numbers starting from +61-493.. are not being validated on Android, affecting production app.

https://github.com/google/libphonenumber/releases

**Comment by acoutts** [comment]
Just pushed in v2.3.3
