### ISSUE TITLE
Xcode 16 Beta build failed to compile

### ISSUE THREAD

**Issue by oleksii-pyvovarov-windmill** [acoutts/flutter_libphonenumber#80]
...Pods/PhoneNumberKit/PhoneNumberKit/ParseManager.swift:112:21: Mutable capture of 'inout' parameter 'buffer' is not allowed in concurrently-executing code

This lib adds pod dependency on https://github.com/marmelroy/PhoneNumberKit.
It had compilation issue for Xcode 16 Beta which was fixed in 3.8.0 version (https://github.com/marmelroy/PhoneNumberKit/issues/796).
For now latest flutter_libphonenumber adds 3.7.9 to cocoa pods.

Can we have a version that uses 3.8.0?

**Comment by acoutts** [comment]
Just pushed in v2.3.2
